### ISSUE TITLE
npm Package

### ISSUE THREAD

**Issue by aaronbach** [sencrop/capacitor-intercom#14]
Hi together,

this plugin is looking pretty promising, because it uses a relatively up to date Intercom SDK Version. At the moment there is no public npm package.

Do you plan to publish it, or do you have instructions, how to build it myself?

Thanks for your work
Cheers

**Comment by Oupsla** [comment]
Hello @aaronbach ,

Sorry for the delay of my answer.
The package was published but was private, I just make it public !

Have a nice day,
Cheers
