### ISSUE TITLE
Migration to the latest version of Intercom

### ISSUE THREAD

**Issue by bastienlemaitre** [sencrop/capacitor-intercom#32]
Hello

I would like to know if it is a problem to switch to the latest versions of Intercom. I know that the SDK min will be much higher.

If that's ok with you, I'll create a merge request for that.

Any advice?

**Comment by Oupsla** [comment]
Hello @bastienlemaitre, it seems that it is ok to bump intercom to the latest version

For android, it seems that it is a minor bump (from 15.2.0 to 15.10.3), did you see somewhere that we should set a higher min sdk ?
I think you just have to set the new version in build.gradle like in [this PR ](https://github.com/sencrop/capacitor-intercom/pull/25/files)

For iOs, it is a major bump (from 16.3.1 to 18.0.0), I don't see any breaking change for the 17 to 18, but for the 16 to 17 there is a warning in the [changelog](https://github.com/intercom/intercom-ios/releases/tag/17.0.0) 

You can try to edit the Podfile, and then do to a pod install (or pod update) and see what happens regarding this warning (like in [this PR ](https://github.com/sencrop/capacitor-intercom/pull/26/files))

**Comment by bastienlemaitre** [comment]
Hi @Oupsla ,
There's my PR: https://github.com/sencrop/capacitor-intercom/pull/33
